# Generated by Django 4.0.5 on 2022-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='cantidadventa',
            field=models.IntegerField(default=0, null=True, verbose_name='cantidad venta'),
        ),
    ]
